### ISSUE TITLE
Feature request: Automatic reconnect to knx server

### ISSUE THREAD

**Issue by endurance1968** [pakerfeldt/knx-mqtt#4]
Wish: reconnect after knx went down and online again.

Oberservation:
If I shut down my KNX network (e.g. power outage) the knx-mqtt bridge does not reconnect to KNX if power is up again.
Restarting the knx-mqtt services solves the problem immediately.

Wanted behaviour: automatic reconnect if knx comes back online.

Note: my knx-mqtt is hosted on a server with a seperate UPS so it should continuously run. But KNX server is not/on another UPS.

```
knx:
  # ETS exported group addresses
  etsExport: '/root/knx-mqtt-main/ets_gruppen_2025_01_06.xml'

  # Address to the KNX gateway
  endpoint: "192.168.1.222:3671"

  # If true, connect over tunnel/unicast, if false use router/multicast.
  tunnelMode: true

  # Ignore unknown group addresses
  ignoreUnknownGroupAddresses: false

  # Enables logging from the KNX library
  enableLogs: false
```
